import json
import os
import stat
import subprocess
import uuid
from dataclasses import dataclass, field, asdict
from pathlib import Path
from datetime import datetime

CONFIG_DIR        = Path.home() / ".config" / "OpenSourceTree"
BOOKMARKS_FILE    = CONFIG_DIR / "bookmarks.json"
SSH_PROFILES_FILE = CONFIG_DIR / "ssh_profiles.json"
ACCOUNTS_FILE     = CONFIG_DIR / "accounts.json"
APP_CONFIG_FILE   = CONFIG_DIR / "app_config.json"
OPENSSH_CONFIG    = CONFIG_DIR / "ssh_config"
ASKPASS_SCRIPT    = CONFIG_DIR / "askpass.py"
AVATARS_DIR       = CONFIG_DIR / "avatars"


def _ensure_config_dir():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    AVATARS_DIR.mkdir(exist_ok=True)
    (Path.home() / ".ssh").mkdir(mode=0o700, exist_ok=True)


# ── App config (language, etc.) ───────────────────────────────────────────────

def get_language() -> str:
    if not APP_CONFIG_FILE.exists():
        return "en"
    try:
        data = json.loads(APP_CONFIG_FILE.read_text(encoding="utf-8"))
        return data.get("language", "en")
    except Exception:
        return "en"


def set_language(code: str) -> None:
    _ensure_config_dir()
    data: dict = {}
    if APP_CONFIG_FILE.exists():
        try:
            data = json.loads(APP_CONFIG_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    data["language"] = code
    APP_CONFIG_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


# ── Bookmarks ────────────────────────────────────────────────────────────────

def load_bookmarks() -> list[str]:
    if not BOOKMARKS_FILE.exists():
        return []
    try:
        with open(BOOKMARKS_FILE) as f:
            data = json.load(f)
        return [p for p in data if os.path.isdir(p)]
    except (json.JSONDecodeError, KeyError):
        return []


def save_bookmarks(paths: list[str]) -> None:
    _ensure_config_dir()
    with open(BOOKMARKS_FILE, "w") as f:
        json.dump(paths, f, indent=2)


def add_bookmark(path: str) -> list[str]:
    bookmarks = load_bookmarks()
    if path not in bookmarks:
        bookmarks.append(path)
        save_bookmarks(bookmarks)
    return bookmarks


def remove_bookmark(path: str) -> list[str]:
    bookmarks = load_bookmarks()
    if path in bookmarks:
        bookmarks.remove(path)
        save_bookmarks(bookmarks)
    return bookmarks


# ── SSH Profiles ─────────────────────────────────────────────────────────────

@dataclass
class SSHProfile:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    key_path: str = ""
    host_alias: str = ""
    hostname: str = ""
    username: str = "git"
    port: int = 22
    strict_host_checking: str = "accept-new"


def load_ssh_profiles() -> list[SSHProfile]:
    if not SSH_PROFILES_FILE.exists():
        return []
    try:
        with open(SSH_PROFILES_FILE) as f:
            data = json.load(f)
        return [SSHProfile(**p) for p in data]
    except Exception:
        return []


def save_ssh_profiles(profiles: list[SSHProfile]) -> None:
    _ensure_config_dir()
    with open(SSH_PROFILES_FILE, "w") as f:
        json.dump([asdict(p) for p in profiles], f, indent=2)
    _write_openssh_config(profiles)


def _write_openssh_config(profiles: list[SSHProfile]) -> None:
    _ensure_config_dir()
    lines = [
        "# Generated by OpenSourceTree — do not edit manually",
        f"# Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]
    by_host: dict[str, list[SSHProfile]] = {}
    for p in profiles:
        if p.hostname:
            by_host.setdefault(p.hostname, []).append(p)

    for profile in profiles:
        if not profile.key_path or not profile.hostname:
            continue
        alias = profile.host_alias or profile.hostname
        same = by_host.get(profile.hostname, [])
        host_line = alias
        if len(same) == 1 and alias != profile.hostname:
            host_line = f"{alias} {profile.hostname}"
        elif len(same) == 1:
            host_line = profile.hostname
        lines += [
            f"# Profile: {profile.name or alias}",
            f"Host {host_line}",
            f"    HostName {profile.hostname}",
            f"    User {profile.username}",
            f"    Port {profile.port}",
            f"    IdentityFile {profile.key_path}",
            "    IdentitiesOnly yes",
            f"    StrictHostKeyChecking {profile.strict_host_checking}",
            "",
        ]
    with open(OPENSSH_CONFIG, "w") as f:
        f.write("\n".join(lines))
    OPENSSH_CONFIG.chmod(0o600)


def get_git_ssh_command() -> str | None:
    profiles = load_ssh_profiles()
    active = [p for p in profiles if p.key_path and p.hostname]
    if not active:
        return None
    _write_openssh_config(profiles)
    return f"ssh -F {OPENSSH_CONFIG}"


def ensure_agent_running() -> bool:
    """Start ssh-agent if not running and inject SSH_AUTH_SOCK into os.environ.
    Returns True if agent is running (or was just started successfully)."""
    if os.environ.get("SSH_AUTH_SOCK"):
        return True
    try:
        result = subprocess.run(
            ["ssh-agent", "-s"], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            return False
        for line in result.stdout.splitlines():
            if "SSH_AUTH_SOCK=" in line:
                os.environ["SSH_AUTH_SOCK"] = line.split("=", 1)[1].split(";")[0]
            elif "SSH_AGENT_PID=" in line:
                os.environ["SSH_AGENT_PID"] = line.split("=", 1)[1].split(";")[0]
    except Exception:
        return False
    return bool(os.environ.get("SSH_AUTH_SOCK"))


def scan_default_ssh_keys() -> list[str]:
    ssh_dir = Path.home() / ".ssh"
    found = []
    for name in ("id_ed25519", "id_rsa", "id_ecdsa", "id_dsa"):
        p = ssh_dir / name
        if p.exists():
            found.append(str(p))
    return found


# ── Accounts ─────────────────────────────────────────────────────────────────

# Known provider defaults
PROVIDERS = {
    "github":    {"label": "GitHub",    "api_url": "https://api.github.com",          "host": "github.com"},
    "gitlab":    {"label": "GitLab",    "api_url": "https://gitlab.com/api/v4",       "host": "gitlab.com"},
    "bitbucket": {"label": "Bitbucket", "api_url": "https://api.bitbucket.org/2.0",   "host": "bitbucket.org"},
    "gitea":     {"label": "Gitea",     "api_url": "",                                "host": ""},
    "custom":    {"label": "Custom",    "api_url": "",                                "host": ""},
}


@dataclass
class Account:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    provider: str = "github"     # key in PROVIDERS or "custom"
    label: str = ""              # display name, e.g. "My GitHub"
    username: str = ""           # git username / login
    email: str = ""              # git author email
    token: str = ""              # personal access token (HTTPS auth)
    api_url: str = ""            # custom API URL (for self-hosted)
    host: str = ""               # git hostname, e.g. github.com
    avatar_path: str = ""        # local cached avatar file


def load_accounts() -> list[Account]:
    if not ACCOUNTS_FILE.exists():
        return []
    try:
        with open(ACCOUNTS_FILE) as f:
            data = json.load(f)
        return [Account(**a) for a in data]
    except Exception:
        return []


def save_accounts(accounts: list[Account]) -> None:
    _ensure_config_dir()
    with open(ACCOUNTS_FILE, "w") as f:
        json.dump([asdict(a) for a in accounts], f, indent=2)
    _write_askpass_script(accounts)


def _write_askpass_script(accounts: list[Account]) -> None:
    """
    Write an executable Python ASKPASS helper that provides credentials
    to git for HTTPS operations. Git calls it with the prompt as argv[1].
    """
    _ensure_config_dir()
    entries = []
    for acc in accounts:
        if not acc.token:
            continue
        host = acc.host or PROVIDERS.get(acc.provider, {}).get("host", "")
        if host:
            entries.append({"host": host, "username": acc.username or "oauth2", "token": acc.token})

    script = (
        "#!/usr/bin/env python3\n"
        "# Generated by OpenSourceTree — do not edit manually\n"
        "import sys, re\n"
        f"ENTRIES = {repr(entries)}\n"
        "prompt = ' '.join(sys.argv[1:]).lower()\n"
        "m = re.search(r\"'https?://[^@']*@?([^/']+)\", prompt)\n"
        "host = m.group(1) if m else ''\n"
        "for e in ENTRIES:\n"
        "    if e['host'] and (host == e['host'] or host.endswith('.' + e['host'])):\n"
        "        print(e['username'] if 'username' in prompt else e['token'])\n"
        "        sys.exit(0)\n"
        "sys.exit(0)\n"
    )
    with open(ASKPASS_SCRIPT, "w") as f:
        f.write(script)
    ASKPASS_SCRIPT.chmod(0o700)


def get_askpass_path() -> str | None:
    """Return ASKPASS script path if any accounts with tokens exist."""
    accounts = load_accounts()
    if any(a.token for a in accounts):
        _write_askpass_script(accounts)
        return str(ASKPASS_SCRIPT)
    return None


def match_account_for_host(host: str) -> Account | None:
    """Find the first account that matches a hostname."""
    for acc in load_accounts():
        acc_host = acc.host or PROVIDERS.get(acc.provider, {}).get("host", "")
        if acc_host and (host == acc_host or host.endswith("." + acc_host)):
            return acc
    return None


def fetch_avatar(account: Account) -> str:
    """
    Download the user's avatar from GitHub/GitLab API.
    Returns local file path, or empty string on failure.
    """
    import urllib.request
    import urllib.error

    _ensure_config_dir()
    api_url = account.api_url or PROVIDERS.get(account.provider, {}).get("api_url", "")
    if not api_url or not account.username:
        return ""

    avatar_url = ""
    headers = {"User-Agent": "OpenSourceTree/0.1"}
    if account.token:
        headers["Authorization"] = f"Bearer {account.token}"

    try:
        if account.provider == "github":
            url = f"{api_url}/users/{account.username}"
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=10) as r:
                data = json.loads(r.read())
            avatar_url = data.get("avatar_url", "")

        elif account.provider == "gitlab":
            url = f"{api_url}/users?username={account.username}"
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=10) as r:
                data = json.loads(r.read())
            if data:
                avatar_url = data[0].get("avatar_url", "")

        if not avatar_url:
            return ""

        dest = AVATARS_DIR / f"{account.id}.png"
        req2 = urllib.request.Request(avatar_url, headers={"User-Agent": "OpenSourceTree/0.1"})
        with urllib.request.urlopen(req2, timeout=10) as r:
            dest.write_bytes(r.read())
        return str(dest)

    except Exception:
        return ""
