import json
import os
import re
import stat
import subprocess
import uuid
from dataclasses import dataclass, field, asdict, fields
from pathlib import Path
from datetime import datetime

CONFIG_DIR        = Path.home() / ".config" / "OpenSourceTree"
BOOKMARKS_FILE    = CONFIG_DIR / "bookmarks.json"
SSH_PROFILES_FILE = CONFIG_DIR / "ssh_profiles.json"
ACCOUNTS_FILE     = CONFIG_DIR / "accounts.json"
APP_CONFIG_FILE   = CONFIG_DIR / "app_config.json"
OPENSSH_CONFIG    = CONFIG_DIR / "ssh_config"
ASKPASS_SCRIPT    = CONFIG_DIR / "askpass.py"
AVATARS_DIR       = CONFIG_DIR / "avatars"


def _ensure_dir(path: Path, mode: int | None = None) -> None:
    """Create `path` as a directory, tolerating anything already sitting there.

    After an accidental deletion, some trash/sync tools on certain distros
    (this has been seen on Equestria OS) don't restore a folder cleanly —
    they can leave a stray plain *file* at that path, or nothing at all one
    level up. A bare `Path.mkdir(exist_ok=True)` raises in that case, and
    since this helper runs before *every* config read/write (bookmarks,
    SSH profiles, accounts, app settings — literally everything), a single
    bad path used to be enough to take down the whole feature set instead
    of just one of them. Move anything unexpected out of the way instead
    of raising, and never let a failure here propagate.
    """
    try:
        if path.exists() and not path.is_dir():
            try:
                path.rename(path.with_name(f"{path.name}.bak-{int(datetime.now().timestamp())}"))
            except OSError:
                try:
                    path.unlink()
                except OSError:
                    return  # can't clear it — leave it, callers will just fail to write
        path.mkdir(parents=True, exist_ok=True)
        if mode is not None:
            try:
                path.chmod(mode)
            except OSError:
                pass
    except OSError:
        pass  # best-effort: never let config-dir setup crash the app


def _ensure_config_dir():
    _ensure_dir(Path.home() / ".config")
    _ensure_dir(CONFIG_DIR)
    _ensure_dir(AVATARS_DIR)
    _ensure_dir(Path.home() / ".ssh", mode=0o700)


# ── App config (language, etc.) ───────────────────────────────────────────────

def get_language() -> str:
    if not APP_CONFIG_FILE.exists():
        return "en"
    try:
        data = json.loads(APP_CONFIG_FILE.read_text(encoding="utf-8"))
        return data.get("language", "en")
    except Exception:
        return "en"


def set_language(code: str) -> None:
    _ensure_config_dir()
    data: dict = {}
    if APP_CONFIG_FILE.exists():
        try:
            data = json.loads(APP_CONFIG_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    data["language"] = code
    APP_CONFIG_FILE.write_text(json.dumps(data, indent=2), encoding="utf-8")


# ── Bookmarks ────────────────────────────────────────────────────────────────

def load_bookmarks() -> list[str]:
    if not BOOKMARKS_FILE.exists():
        return []
    try:
        with open(BOOKMARKS_FILE) as f:
            data = json.load(f)
        return [p for p in data if os.path.isdir(p)]
    except (json.JSONDecodeError, KeyError):
        return []


def save_bookmarks(paths: list[str]) -> None:
    _ensure_config_dir()
    with open(BOOKMARKS_FILE, "w") as f:
        json.dump(paths, f, indent=2)


def add_bookmark(path: str) -> list[str]:
    bookmarks = load_bookmarks()
    if path not in bookmarks:
        bookmarks.append(path)
        save_bookmarks(bookmarks)
    return bookmarks


def remove_bookmark(path: str) -> list[str]:
    bookmarks = load_bookmarks()
    if path in bookmarks:
        bookmarks.remove(path)
        save_bookmarks(bookmarks)
    return bookmarks


# ── SSH Profiles ─────────────────────────────────────────────────────────────

@dataclass
class SSHProfile:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    key_path: str = ""
    host_alias: str = ""
    hostname: str = ""
    username: str = "git"
    port: int = 22
    strict_host_checking: str = "accept-new"


def load_ssh_profiles() -> list[SSHProfile]:
    if not SSH_PROFILES_FILE.exists():
        return []
    try:
        with open(SSH_PROFILES_FILE) as f:
            data = json.load(f)
        known = {f.name for f in fields(SSHProfile)}
        return [SSHProfile(**{k: v for k, v in p.items() if k in known}) for p in data]
    except Exception:
        return []


def save_ssh_profiles(profiles: list[SSHProfile]) -> None:
    _ensure_config_dir()
    with open(SSH_PROFILES_FILE, "w") as f:
        json.dump([asdict(p) for p in profiles], f, indent=2)
    _write_openssh_config(profiles)


def _write_openssh_config(profiles: list[SSHProfile]) -> None:
    _ensure_config_dir()
    lines = [
        "# Generated by OpenSourceTree — do not edit manually",
        f"# Updated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]
    by_host: dict[str, list[SSHProfile]] = {}
    for p in profiles:
        if p.hostname:
            by_host.setdefault(p.hostname, []).append(p)

    for profile in profiles:
        if not profile.key_path or not profile.hostname:
            continue
        alias = profile.host_alias or profile.hostname
        same = by_host.get(profile.hostname, [])
        host_line = alias
        if len(same) == 1 and alias != profile.hostname:
            host_line = f"{alias} {profile.hostname}"
        elif len(same) == 1:
            host_line = profile.hostname
        lines += [
            f"# Profile: {profile.name or alias}",
            f"Host {host_line}",
            f"    HostName {profile.hostname}",
            f"    User {profile.username}",
            f"    Port {profile.port}",
            f"    IdentityFile {profile.key_path}",
            "    IdentitiesOnly yes",
            f"    StrictHostKeyChecking {profile.strict_host_checking}",
            "",
        ]
    with open(OPENSSH_CONFIG, "w") as f:
        f.write("\n".join(lines))
    OPENSSH_CONFIG.chmod(0o600)


def get_git_ssh_command() -> str | None:
    profiles = load_ssh_profiles()
    active = [p for p in profiles if p.key_path and p.hostname]
    if not active:
        return None
    _write_openssh_config(profiles)
    return f"ssh -F {OPENSSH_CONFIG}"


AGENT_SOCK = CONFIG_DIR / "ssh-agent.sock"
_agent_verified_this_run = False


def _agent_alive(sock_path: str) -> bool:
    """True if an ssh-agent is actually listening (and reachable) at sock_path.

    `ssh-add -l` exits 0 (has keys) or 1 (reachable, just empty) when the
    agent is alive; 2 means the socket is missing/stale/unreachable.
    """
    try:
        result = subprocess.run(
            ["ssh-add", "-l"],
            env={**os.environ, "SSH_AUTH_SOCK": sock_path},
            capture_output=True, timeout=5,
        )
        return result.returncode in (0, 1)
    except Exception:
        return False


def _shell_profile_agent_sock() -> str | None:
    """SSH_AUTH_SOCK from ~/.ssh-agent-info, the file this user's own
    ~/.bashrc writes when it autostarts an ssh-agent for interactive shells.

    A desktop launcher never sources ~/.bashrc, so it can't inherit that
    agent's env the way a terminal-opened app would -- but the socket it
    published is still just as reusable. Checking this file lets us find and
    reuse that agent instead of spawning a second, empty one.
    """
    info_file = Path.home() / ".ssh-agent-info"
    if not info_file.exists():
        return None
    try:
        match = re.search(r"SSH_AUTH_SOCK=([^;\s]+)", info_file.read_text())
    except OSError:
        return None
    return match.group(1) if match else None


def ensure_agent_running() -> bool:
    """Get a usable ssh-agent into os.environ["SSH_AUTH_SOCK"], reusing a
    persistent one across app restarts instead of spawning a fresh empty
    agent every launch.

    Desktop launchers (app menu / .desktop entries, as opposed to a
    terminal) frequently don't propagate a session's SSH_AUTH_SOCK into the
    process they start, even when a perfectly good agent is already
    running. The old code treated a missing env var as "no agent" and
    spawned a brand new throwaway one on every single launch -- each one an
    orphan process once the app closed, and each one empty, so any key
    added via ssh-add (passphrase prompt and all) only lived as long as
    that one run.

    Fix: bind our own agent to a fixed socket path under the config dir on
    first use, and on every subsequent call just check whether it's still
    alive and reuse it. A key added to it via ssh-add then survives app
    restarts -- the passphrase is only needed again after a reboot/logout
    (or if the agent is killed manually), not on every launch.

    Once this succeeds, the result is cached for the rest of the process
    (`_agent_verified_this_run`) so callers that just want SSH_AUTH_SOCK
    populated before a network git command -- e.g. GitRunner on every call
    -- don't pay for an `ssh-add -l` round trip each time.
    """
    global _agent_verified_this_run
    if _agent_verified_this_run:
        return True

    if _agent_alive(str(AGENT_SOCK)):
        os.environ["SSH_AUTH_SOCK"] = str(AGENT_SOCK)
        _agent_verified_this_run = True
        return True

    # A session-provided agent (KDE Wallet, gnome-keyring, systemd --user
    # ssh-agent.socket, ...) is just as good if this process happens to
    # have inherited it -- prefer it over spawning our own.
    inherited = os.environ.get("SSH_AUTH_SOCK")
    if inherited and _agent_alive(inherited):
        _agent_verified_this_run = True
        return True

    shell_sock = _shell_profile_agent_sock()
    if shell_sock and _agent_alive(shell_sock):
        os.environ["SSH_AUTH_SOCK"] = shell_sock
        _agent_verified_this_run = True
        return True

    _ensure_config_dir()
    try:
        if AGENT_SOCK.exists():
            AGENT_SOCK.unlink()  # stale socket left by a dead agent
        result = subprocess.run(
            ["ssh-agent", "-a", str(AGENT_SOCK)],
            capture_output=True, timeout=10,
        )
        if result.returncode != 0:
            return False
    except Exception:
        return False

    os.environ["SSH_AUTH_SOCK"] = str(AGENT_SOCK)
    ok = _agent_alive(str(AGENT_SOCK))
    _agent_verified_this_run = ok
    return ok


def scan_default_ssh_keys() -> list[str]:
    ssh_dir = Path.home() / ".ssh"
    found = []
    for name in ("id_ed25519", "id_rsa", "id_ecdsa", "id_dsa"):
        p = ssh_dir / name
        if p.exists():
            found.append(str(p))
    return found


# ── Accounts ─────────────────────────────────────────────────────────────────

# Known provider defaults
PROVIDERS = {
    "github":    {"label": "GitHub",    "api_url": "https://api.github.com",          "host": "github.com"},
    "gitlab":    {"label": "GitLab",    "api_url": "https://gitlab.com/api/v4",       "host": "gitlab.com"},
    "bitbucket": {"label": "Bitbucket", "api_url": "https://api.bitbucket.org/2.0",   "host": "bitbucket.org"},
    "gitea":     {"label": "Gitea",     "api_url": "",                                "host": ""},
    "custom":    {"label": "Custom",    "api_url": "",                                "host": ""},
}


@dataclass
class Account:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    provider: str = "github"     # key in PROVIDERS or "custom"
    label: str = ""              # display name, e.g. "My GitHub"
    username: str = ""           # git username / login
    email: str = ""              # git author email
    token: str = ""              # personal access token (HTTPS auth)
    api_url: str = ""            # custom API URL (for self-hosted)
    host: str = ""               # git hostname, e.g. github.com
    avatar_path: str = ""        # local cached avatar file


def load_accounts() -> list[Account]:
    if not ACCOUNTS_FILE.exists():
        return []
    try:
        with open(ACCOUNTS_FILE) as f:
            data = json.load(f)
        return [Account(**a) for a in data]
    except Exception:
        return []


def save_accounts(accounts: list[Account]) -> None:
    _ensure_config_dir()
    with open(ACCOUNTS_FILE, "w") as f:
        json.dump([asdict(a) for a in accounts], f, indent=2)
    _write_askpass_script(accounts)


def _write_askpass_script(accounts: list[Account]) -> None:
    """
    Write an executable Python ASKPASS helper that provides credentials
    to git for HTTPS operations. Git calls it with the prompt as argv[1].
    """
    _ensure_config_dir()
    entries = []
    for acc in accounts:
        if not acc.token:
            continue
        host = acc.host or PROVIDERS.get(acc.provider, {}).get("host", "")
        if host:
            entries.append({"host": host, "username": acc.username or "oauth2", "token": acc.token})

    script = (
        "#!/usr/bin/env python3\n"
        "# Generated by OpenSourceTree — do not edit manually\n"
        "import sys, re\n"
        f"ENTRIES = {repr(entries)}\n"
        "prompt = ' '.join(sys.argv[1:]).lower()\n"
        "m = re.search(r\"'https?://[^@']*@?([^/']+)\", prompt)\n"
        "host = m.group(1) if m else ''\n"
        "for e in ENTRIES:\n"
        "    if e['host'] and (host == e['host'] or host.endswith('.' + e['host'])):\n"
        "        print(e['username'] if 'username' in prompt else e['token'])\n"
        "        sys.exit(0)\n"
        "sys.exit(0)\n"
    )
    with open(ASKPASS_SCRIPT, "w") as f:
        f.write(script)
    ASKPASS_SCRIPT.chmod(0o700)


def get_askpass_path() -> str | None:
    """Return ASKPASS script path if any accounts with tokens exist."""
    accounts = load_accounts()
    if any(a.token for a in accounts):
        _write_askpass_script(accounts)
        return str(ASKPASS_SCRIPT)
    return None


def match_account_for_host(host: str) -> Account | None:
    """Find the first account that matches a hostname."""
    for acc in load_accounts():
        acc_host = acc.host or PROVIDERS.get(acc.provider, {}).get("host", "")
        if acc_host and (host == acc_host or host.endswith("." + acc_host)):
            return acc
    return None


def fetch_avatar(account: Account) -> str:
    """
    Download the user's avatar from GitHub/GitLab API.
    Returns local file path, or empty string on failure.
    """
    import urllib.request
    import urllib.error

    _ensure_config_dir()
    api_url = account.api_url or PROVIDERS.get(account.provider, {}).get("api_url", "")
    if not api_url or not account.username:
        return ""

    avatar_url = ""
    headers = {"User-Agent": "OpenSourceTree/0.1"}
    if account.token:
        headers["Authorization"] = f"Bearer {account.token}"

    try:
        if account.provider == "github":
            url = f"{api_url}/users/{account.username}"
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=10) as r:
                data = json.loads(r.read())
            avatar_url = data.get("avatar_url", "")

        elif account.provider == "gitlab":
            url = f"{api_url}/users?username={account.username}"
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=10) as r:
                data = json.loads(r.read())
            if data:
                avatar_url = data[0].get("avatar_url", "")

        if not avatar_url:
            return ""

        dest = AVATARS_DIR / f"{account.id}.png"
        req2 = urllib.request.Request(avatar_url, headers={"User-Agent": "OpenSourceTree/0.1"})
        with urllib.request.urlopen(req2, timeout=10) as r:
            dest.write_bytes(r.read())
        return str(dest)

    except Exception:
        return ""
